name: null
favicon: null
layout_spectrum: 0.8
typography_spectrum: 0.5
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#151515'
    - '#edeee6'
    - '#981e1c'
    - '#333b6b'
    - '#756e4e'
  brandStrength: 0.875
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose:
  - name: awareness
    item: null
    url: null
